name: EBAC CI

on:
  push:
    branches: [ci]

workflow_dispatch:

jobs:
  test:
    runs-on: unbuntu-latest

   steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
      node-version: 20
    - name: Cypress run
      uses: cypress-io/github-action@v6
      continue-on-error: true
      with:
        install-command: npm install
        browser: chrome
    - name: Publish Report
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./mochawesome-report
